# Generated by Django 3.2.9 on 2022-03-15 13:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao_Dinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_de_avaliacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('rg', models.IntegerField()),
                ('cff', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('1', 'Dinâmica'), ('2', 'Entrevista'), ('3', 'Pré-Aprovado')], default='1', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('duracao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('desc', models.EmailField(max_length=255)),
                ('duracao', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_vaga', models.IntegerField()),
                ('dataInicio', models.DateTimeField(default=datetime.datetime(2022, 3, 15, 10, 12, 24, 897553))),
                ('dataFechamento', models.DateTimeField(default=datetime.datetime(2022, 3, 15, 10, 12, 24, 897553), null=True)),
                ('fk_id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga_Dinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_dinamica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dinamica')),
                ('fk_id_vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta_Dinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('fk_id_avaliacao_dinamica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.avaliacao_dinamica')),
                ('fk_id_candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidato')),
                ('fk_id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_id_vaga_dinamica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vaga_dinamica')),
            ],
        ),
        migrations.CreateModel(
            name='Observacao_Geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('fk_id_candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidato')),
                ('fk_id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_id_vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vaga')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao_dinamica',
            name='fk_id_dinamica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dinamica'),
        ),
        migrations.CreateModel(
            name='Aprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.candidato')),
                ('fk_id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_id_vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vaga')),
            ],
        ),
    ]
