# Generated by Django 3.2.9 on 2022-03-31 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime(2022, 3, 31, 8, 25, 10, 445055)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(default=datetime.datetime(2022, 3, 31, 8, 25, 10, 446052)),
        ),
    ]
