# Generated by Django 3.2.9 on 2022-03-24 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 8, 55, 10, 466299)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 8, 55, 10, 466299)),
        ),
    ]
