# Generated by Django 3.2.9 on 2022-03-22 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220322_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinamica',
            old_name='descicao',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 10, 52, 33, 949629)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 10, 52, 33, 949629)),
        ),
    ]
