# Generated by Django 3.2.9 on 2022-03-24 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220324_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagadinamica',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 9, 19, 56, 192032)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 9, 19, 56, 192032)),
        ),
    ]
