# Generated by Django 3.2.9 on 2022-05-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_curso_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imgCurso',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
    ]
