# Generated by Django 3.2.9 on 2022-03-22 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220322_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 11, 24, 23, 989393)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 11, 24, 23, 989393)),
        ),
    ]
