# Generated by Django 3.2.9 on 2022-03-23 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220322_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime(2022, 3, 23, 11, 7, 23, 871978)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(default=datetime.datetime(2022, 3, 23, 11, 7, 23, 871978)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dinamica',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='observacao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='statusentrevista',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statusvaga',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
