# Generated by Django 3.2.9 on 2022-03-23 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220323_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime(2022, 3, 23, 11, 19, 37, 776912)),
        ),
        migrations.AlterField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(default=datetime.datetime(2022, 3, 23, 11, 19, 37, 776912)),
        ),
    ]
