# Generated by Django 3.2.9 on 2022-03-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edv',
            field=models.IntegerField(),
        ),
    ]
