# Generated by Django 3.2.9 on 2022-05-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
    ]
